To Do List: Code Review
Recillah-Khamala/To-Do-List-Code-Review pull request #1
Opened 2022-08-16 17:09 UTC by Rn486

### **To Do List: Code Review**

In this pull request, I have copied my code from the "To Do list" project and committed it as one big chunk of code in the feature branch for my partner to review it.

2022-08-16 18:00 UTC, samlorlah commented
Hi @Rn486 ✋,

Good job so far! 👏
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>


### Highlights 💪

- Descriptive pull request ✔️
- No linter errors ✔️
- Good presentation demo ✔️
- JavaScript best practices ✔️
- HTML and CSS best practices ✔️
- Good use of DRY, KISS, and YAGNI rules ✔️

### Required Changes ♻️
Check the comments under the review.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

2022-08-16 18:10 UTC, samlorlah requested changes

2022-08-16 18:10 UTC, samlorlah commented on src/crud.js
> +    index: store.length,
- [ ] Kindly update your index to start from 1 according to the instruction. Update your code at this point to have your task index as requested

2022-08-16 18:10 UTC, samlorlah commented on src/crud.js
> +};
- [ ] When the window refresh button is pressed, the local storage state should not be altered. Kindly reverse the code.

2022-08-16 18:10 UTC, samlorlah commented on src/crud.js
> +    // const item = parseInt(clicked.getAttribute('data-desc', 10));
- [ ] According to YAGNI rule, this should be removed please

2022-08-16 18:10 UTC, samlorlah commented on src/crud.js
> +//   const store = (localStorage.getItem('store')) ? JSON.parse(localStorage.getItem('store')) : [];
- [ ] According to YAGNI rule, this should be removed please

2022-08-18 12:50 UTC, Rn486 commented on src/crud.js
> +    // const item = parseInt(clicked.getAttribute('data-desc', 10));
done

2022-08-18 12:50 UTC, Rn486 commented on src/crud.js
> +    index: store.length,
Done.

2022-08-18 12:50 UTC, Rn486 commented on src/crud.js
> +//   const store = (localStorage.getItem('store')) ? JSON.parse(localStorage.getItem('store')) : [];
Done

2022-08-18 13:12 UTC, samlorlah approved these changes
<img src="https://media4.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

### STATUS: APPROVED!!!  🎉 🎉 🎉 🍾 🍾 🍾

Hi [@Rn486](https://github.com/Rn486),
Good job !!!

To Highlight! 👏 🟢
✔️ Good commit messages
✔️ Descriptive Readme file
✔️ Clean/Organized code

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉 🎉 🎉 🍾 🍾 🍾

2023-04-06 01:46 UTC, merged